In [17]:
import math
import numpy as np

In [ ]:
# nsarray -> n dimensional array
arr = np.array([1, 2, 3, 4, 5])

print(arr)
arr[0] = 69
print(arr[0])
print(arr[:3])

arr2 = arr[3:]
print(arr2)
arr2[0] = 69
print(arr) # arr will also be modified

[1 2 3 4 5]
69
[69  2  3]
[4 5]
[69  2  3 69  5]


In [22]:
# 2d array
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print('Matrix:', matrix)
print('ndim:', matrix.ndim)
print('shape:', matrix.shape) # (2, 3) -> 2 rows and 3 cols
print('size:', matrix.size) # tells the total number of elements
print('mat[1][2]:', matrix[1, 2]) # you can pass indexes separated by comma (can't be done in normal arrays)

Matrix: [[1 2 3]
 [4 5 6]]
ndim: 2
shape: (2, 3)
size: 6
mat[1][2]: 6


> Sometimes `axis` is referred in place of dimensions of array, this is to disambiguate between dimensions of an array and the dimensions of the data represented by the array.

### **Array Operations -**

In [12]:
scalar = np.array(2)
print(scalar) # an array with 0-dimensions is referred to a `scalar`
print(scalar.ndim)

2
0


In [23]:
# ndim tells the cound of dimensions and shape tells the row and col count
print(matrix.ndim == len(matrix.shape))

print(matrix.size == math.prod(matrix.shape))

True
True


In [26]:
# to check the data type of elements of array
print(matrix.dtype)
matrix.dtype

int32


dtype('int32')

In [46]:
# creating basic arrays

print(np.zeros(3))

print(np.ones(2))

print(np.empty(3)) # initial content is random

print(np.arange(5))

print(np.arange(3, 10, 2))

print(np.linspace(0, 10, 5)) # to create values that are spaced linearly in a specific interval

[0. 0. 0.]
[1. 1.]
[0. 0. 0.]
[0 1 2 3 4]
[3 5 7 9]
[ 0.   2.5  5.   7.5 10. ]


In [47]:
# specifying your data type

x = np.ones(3, dtype=np.int64)
print(x)
print(x.dtype)

[1 1 1]
int64


### **Adding, Removing and Sorting Elements -** 

In [51]:
nums = np.array([3, 5, 1, 8, 4, 7, 2])

print(np.sort(nums))
print(nums)

[1 2 3 4 5 7 8]
[3 5 1 8 4 7 2]


In [53]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7])